spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-230-149-169.compute-1.amazonaws.com:5432/d36h5m8o1oc299
    username: biiyrbzwjsqdpq
    password: 9ff9b6ddbe7dc93483dd4662d49ef00bf0c898ccebd8bdc8e21483e91b1bcad4
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
    generate-ddl: true