spring:
  cache.type: none
  devtools.restart.enabled: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-200-72-77.compute-1.amazonaws.com:5432/d95gbs2asgn7um
    username: rwgurhuzidcdbh
    password: 07bef6e9e5d65b1f76413c1f9c4cabaeb56824ca40be8ccb4d30e4590433c5bc
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      org.hibernate.envers.audit_table_prefix: AUD_
      org.hibernate.envers.audit_table_suffix: null